version: '3'
services:
  web:
    build: .
    environment:
      PORT: 3000
    volumes:
      - .:/app
      - bundle:/usr/local/bundle:delegated
      - node_modules:/app/node_modules:delegated
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
volumes:
  bundle:
  db-volume:
  node_modules:
